version: "3"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
  mssql-server-db:
    container_name: dtc2
    restart: always
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyRoot12345!"
      ACCEPT_EULA: "Y"
